services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:stable
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - TZ=America/Bogota
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - ollama
      - postgres

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  postgres:
    image: postgres:16
    container_name: claustrosf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: claustrosf_user
      POSTGRES_PASSWORD: claustrosf_password
      POSTGRES_DB: claustrosf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  ollama_data:
  postgres_data: